alter policy app_content_blocks_write_admin on public.app_content_blocks to authenticated;
alter policy document_types_write_admin on public.document_types to authenticated;
alter policy employee_devices_insert on public.employee_devices to authenticated;
alter policy employee_devices_select on public.employee_devices to authenticated;
alter policy employee_devices_update on public.employee_devices to authenticated;
alter policy employee_push_tokens_delete_self on public.employee_push_tokens to authenticated;
alter policy employee_push_tokens_insert_self on public.employee_push_tokens to authenticated;
alter policy employee_push_tokens_select_self on public.employee_push_tokens to authenticated;
alter policy employee_push_tokens_update_self on public.employee_push_tokens to authenticated;
alter policy employee_sites_select_owner on public.employee_sites to authenticated;
alter policy employee_sites_select_self on public.employee_sites to authenticated;
alter policy employee_sites_write_admin on public.employee_sites to authenticated;
alter policy employee_sites_write_owner on public.employee_sites to authenticated;
alter policy employees_select_area on public.employees to authenticated;
alter policy employees_select_self on public.employees to authenticated;
alter policy "Employees can view LPN items of their sites" on public.inventory_lpn_items to authenticated;
alter policy "Staff can manage LPN items" on public.inventory_lpn_items to authenticated;
alter policy support_messages_insert on public.support_messages to authenticated;
alter policy support_messages_select on public.support_messages to authenticated;
alter policy support_tickets_insert on public.support_tickets to authenticated;
alter policy support_tickets_select on public.support_tickets to authenticated;
alter policy support_tickets_update on public.support_tickets to authenticated;